title: Parvathy Sailesh
logo: assets/Website headshot_circle.png
description: parvathy.sailesh@u.nus.edu
show_downloads: false
theme: jekyll-theme-minimal
markdown: kramdown
include:
  - assets/css/custom.css
